title: WhatsApp Chat Viewer
logo: logo.png
description: A sleek and efficient tool for viewing exported WhatsApp chats with customizable themes.  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
show_navbar: true
show_footer: true
